CREATE TABLE IF NOT EXISTS vacancies (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hh_id VARCHAR(64),
    title VARCHAR(512),
    company VARCHAR(256),
    salary_from INTEGER DEFAULT 0,
    salary_to INTEGER DEFAULT 0,
    currency VARCHAR(8) DEFAULT 'RUR',
    address VARCHAR(512),
    district VARCHAR(256),
    url VARCHAR(1024),
    ai_score INTEGER DEFAULT 0,
    ai_verdict VARCHAR(32) DEFAULT 'pending',
    ai_reason VARCHAR(512),
    description TEXT,
    status VARCHAR(32) DEFAULT 'new',
    rejection_reason VARCHAR(512),
    notes VARCHAR(2048),
    applied_at VARCHAR(64),
    created_at VARCHAR(64),
    updated_at VARCHAR(64),
    source VARCHAR(32) DEFAULT 'hh',
    source_query VARCHAR(256),
    is_remote BOOLEAN DEFAULT FALSE,
    notified BOOLEAN DEFAULT FALSE,
    published_at VARCHAR(64),
    found_by_scan INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS tags (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vacancy_id INTEGER NOT NULL,
    name VARCHAR(64) NOT NULL,
    FOREIGN KEY (vacancy_id) REFERENCES vacancies(id)
);

CREATE TABLE IF NOT EXISTS history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vacancy_id INTEGER NOT NULL,
    action VARCHAR(64) NOT NULL,
    details VARCHAR(512),
    created_at VARCHAR(64),
    FOREIGN KEY (vacancy_id) REFERENCES vacancies(id)
);

CREATE INDEX IF NOT EXISTS idx_vacancies_status ON vacancies(status);
CREATE INDEX IF NOT EXISTS idx_vacancies_hh_id ON vacancies(hh_id);
CREATE INDEX IF NOT EXISTS idx_vacancies_ai ON vacancies(ai_verdict, ai_score);
CREATE INDEX IF NOT EXISTS idx_tags_vacancy ON tags(vacancy_id);
