CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(128) NOT NULL UNIQUE,
    password_hash VARCHAR(256) NOT NULL,
    display_name VARCHAR(128) NOT NULL,
    role VARCHAR(16) NOT NULL DEFAULT 'user',
    city VARCHAR(128) DEFAULT '',
    experience_summary VARCHAR(2048) DEFAULT '',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS searches (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    name VARCHAR(128) NOT NULL,
    queries VARCHAR(4096) NOT NULL DEFAULT '[]',
    area INTEGER NOT NULL DEFAULT 113,
    schedule VARCHAR(32) DEFAULT '',
    salary_min INTEGER DEFAULT 0,
    priority_districts VARCHAR(2048) DEFAULT '[]',
    skills VARCHAR(2048) DEFAULT '[]',
    not_suitable VARCHAR(2048) DEFAULT '[]',
    exclude_words VARCHAR(2048) DEFAULT '[]',
    ai_notes VARCHAR(2048) DEFAULT '',
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at VARCHAR(64) NOT NULL,
    updated_at VARCHAR(64) NOT NULL,
    is_global BOOLEAN NOT NULL DEFAULT FALSE,
    source_url VARCHAR(1024) DEFAULT '',
    run_interval_hours INTEGER DEFAULT NULL,
    last_run_at VARCHAR(64) DEFAULT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE(user_id, name)
);

CREATE TABLE IF NOT EXISTS vacancies (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hh_id VARCHAR(64),
    person VARCHAR(128) DEFAULT '',
    search_name VARCHAR(128) DEFAULT '',
    user_id INTEGER DEFAULT NULL,
    search_id INTEGER DEFAULT NULL,
    criteria_hash VARCHAR(128) DEFAULT '',
    title VARCHAR(512),
    company VARCHAR(256),
    employer_name VARCHAR(256) DEFAULT '',
    salary_from INTEGER DEFAULT 0,
    salary_to INTEGER DEFAULT 0,
    currency VARCHAR(8) DEFAULT 'RUR',
    salary_gross BOOLEAN DEFAULT FALSE,
    address VARCHAR(512),
    district VARCHAR(256),
    url VARCHAR(1024),
    experience VARCHAR(128) DEFAULT '',
    employment VARCHAR(128) DEFAULT '',
    key_skills VARCHAR(2048) DEFAULT '',
    trusted_employer BOOLEAN DEFAULT FALSE,
    valid_through VARCHAR(64) DEFAULT '',
    scrape_status VARCHAR(32) DEFAULT 'pending',
    ai_score INTEGER DEFAULT 0,
    ai_verdict VARCHAR(32) DEFAULT 'pending',
    ai_reason VARCHAR(512),
    description TEXT,
    status VARCHAR(32) DEFAULT 'new',
    rejection_reason VARCHAR(512),
    notes VARCHAR(2048),
    applied_at VARCHAR(64),
    created_at VARCHAR(64),
    updated_at VARCHAR(64),
    source VARCHAR(32) DEFAULT 'hh',
    source_query VARCHAR(256),
    is_remote BOOLEAN DEFAULT FALSE,
    notified BOOLEAN DEFAULT FALSE,
    published_at VARCHAR(64),
    found_by_scan INTEGER DEFAULT 0,
    dedup_key VARCHAR(512) DEFAULT '',
    UNIQUE(hh_id, person, search_name)
);

CREATE TABLE IF NOT EXISTS user_vacancy_status (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL,
    vacancy_id INTEGER NOT NULL,
    status VARCHAR(32) NOT NULL DEFAULT 'new',
    rejection_reason VARCHAR(512) DEFAULT '',
    notes VARCHAR(2048) DEFAULT '',
    applied_at VARCHAR(64) DEFAULT '',
    updated_at VARCHAR(64) NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (vacancy_id) REFERENCES vacancies(id) ON DELETE CASCADE,
    UNIQUE(user_id, vacancy_id)
);

CREATE TABLE IF NOT EXISTS tags (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vacancy_id INTEGER NOT NULL,
    name VARCHAR(64) NOT NULL,
    FOREIGN KEY (vacancy_id) REFERENCES vacancies(id)
);

CREATE TABLE IF NOT EXISTS history (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    vacancy_id INTEGER NOT NULL,
    action VARCHAR(64) NOT NULL,
    details VARCHAR(512),
    created_at VARCHAR(64),
    FOREIGN KEY (vacancy_id) REFERENCES vacancies(id)
);

CREATE INDEX IF NOT EXISTS idx_vacancies_status ON vacancies(status);
CREATE INDEX IF NOT EXISTS idx_vacancies_hh_id ON vacancies(hh_id);
CREATE INDEX IF NOT EXISTS idx_vacancies_ai ON vacancies(ai_verdict, ai_score);
CREATE INDEX IF NOT EXISTS idx_vacancies_user_id ON vacancies(user_id);
CREATE INDEX IF NOT EXISTS idx_vacancies_person_search ON vacancies(person, search_name);
CREATE INDEX IF NOT EXISTS idx_tags_vacancy ON tags(vacancy_id);
CREATE INDEX IF NOT EXISTS idx_searches_user_id ON searches(user_id);
CREATE INDEX IF NOT EXISTS idx_searches_is_global ON searches(is_global);
CREATE INDEX IF NOT EXISTS idx_vacancies_dedup_key ON vacancies(dedup_key);
CREATE INDEX IF NOT EXISTS idx_uvs_user_id ON user_vacancy_status(user_id);
CREATE INDEX IF NOT EXISTS idx_uvs_vacancy_id ON user_vacancy_status(vacancy_id);
